# Generated by Django 3.1.7 on 2021-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=256, unique=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=512)),
            ],
        ),
    ]
