# Generated by Django 3.1.7 on 2021-03-20 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=256, unique=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=512)),
                ('is_folder', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='api.file')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='api.file')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.file')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('share_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['folder'], name='api_folder_folder__d5f1db_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['file'], name='api_folder_file_id_e78651_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_id'], name='api_file_file_id_f5890f_idx'),
        ),
        migrations.AddIndex(
            model_name='access',
            index=models.Index(fields=['file_id'], name='api_access_file_id_99fdf4_idx'),
        ),
    ]
