# Generated by Django 3.1.7 on 2021-03-19 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210317_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
            preserve_default=False,
        ),
    ]
