# Generated by Django 3.1.7 on 2021-03-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_file_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.file')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backends_Users_related', to=settings.AUTH_USER_MODEL)),
                ('share_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
