version: "3"

services:
  web:
    build: .
    command: python manage.py collectstatic
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./files:/files
      - ./mangoCloud/db.sqlite3:/mangoCloud/db.sqlite3
    ports:
      - "80:8000"
volumes:
  files: