# Generated by Django 3.1.7 on 2021-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
